# Server configurations
rabbit:
  host: "localhost"
  port: 5672
  username: "user"
  password: "bitnami"

# Database credentials
database:
  user: "admin"
  pass: "super-pedro-1980"

gmailSender:
  host: "smtp.gmail.com"
  port: 587
  username: "solhi.amir1371@gmail.com"
  password: "tvtaeifhwbtddsag"

outlookSender:
  host: "smtp-mail.outlook.com"
  port: 587
  username: "test_smtp22@outlook.com"
  password: "Mohsen0000"
